name = "bun-next-todo"
main = ".open-next/worker.js"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_CLOUDFLARE = "true"

[[d1_databases]]
binding = "DB"
database_name = "bun-next-todo"
database_id = "259b3d0c-5d5a-45ae-b238-8d4af24bc1cf"
migrations_dir = "drizzle"
preview_database_id = "DB"                           # Required for Pages local development

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

